"""empty message

Revision ID: 72e4947b1a02
Revises: adc0b5aa9c96
Create Date: 2023-08-06 23:05:14.524936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e4947b1a02'
down_revision = 'adc0b5aa9c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoursePrerequisite',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.drop_table('Course_Prerequisite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course_Prerequisite',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id', name='Course_Prerequisite_pkey')
    )
    op.drop_table('CoursePrerequisite')
    # ### end Alembic commands ###
