"""hey

Revision ID: 08f576f15dd7
Revises: 79c8dbdcc1d8
Create Date: 2023-08-14 18:42:52.277573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f576f15dd7'
down_revision = '79c8dbdcc1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('course_level', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('Student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('current_course', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('currentweekly_module', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('Teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('student')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('course',
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('course_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('course_id', name='course_pkey')
    )
    op.create_table('student',
    sa.Column('student_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('school_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_course', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currentweekly_module', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name='student_pkey')
    )
    op.drop_table('User')
    op.drop_table('Teacher')
    op.drop_table('Student')
    op.drop_table('Course')
    # ### end Alembic commands ###
