"""hey

Revision ID: 3446ca30c8c6
Revises: 64eb63101989
Create Date: 2023-08-14 20:00:37.491906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3446ca30c8c6'
down_revision = '64eb63101989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student_Course', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Course', ['course_id'], ['course_id'])
        batch_op.create_foreign_key(None, 'Student', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student_Course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
