"""mcq

Revision ID: 49aaeada893c
Revises: eaa661a1dddb
Create Date: 2023-08-15 22:12:57.945232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49aaeada893c'
down_revision = 'eaa661a1dddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MCQ',
    sa.Column('mcq_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ),
    sa.PrimaryKeyConstraint('mcq_id')
    )
    op.create_table('ProgrammingProblem',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('problem', sa.String(length=1000), nullable=False),
    sa.Column('sample_input', sa.String(length=500), nullable=False),
    sa.Column('sample_output', sa.String(length=500), nullable=False),
    sa.Column('testing_input', sa.String(length=1000), nullable=False),
    sa.Column('testing_output', sa.String(length=1000), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_table('MCQOption',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('option_label', sa.String(length=1), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('mcq_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mcq_id'], ['MCQ.mcq_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MCQOption')
    op.drop_table('ProgrammingProblem')
    op.drop_table('MCQ')
    # ### end Alembic commands ###
