"""empty message

Revision ID: 59550c3a98d9
Revises: 72e4947b1a02
Create Date: 2023-08-06 23:07:43.240268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59550c3a98d9'
down_revision = '72e4947b1a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course_Prerequisite',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('current_course', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('currentweekly_module', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.drop_table('CoursePrerequisite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoursePrerequisite',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id', name='CoursePrerequisite_pkey')
    )
    op.drop_table('student')
    op.drop_table('Course_Prerequisite')
    # ### end Alembic commands ###
