"""hey

Revision ID: 616cd39cc497
Revises: 08f576f15dd7
Create Date: 2023-08-14 19:02:15.960025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616cd39cc497'
down_revision = '08f576f15dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Course_Prerequisite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Course', ['prerequisite_id'], ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Course_Prerequisite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
