"""empty message

Revision ID: 8c8c4a3bb65d
Revises: f94c7035d4a2
Create Date: 2023-08-06 22:10:00.412965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8c4a3bb65d'
down_revision = 'f94c7035d4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('course_level', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
