"""empty message

Revision ID: adc0b5aa9c96
Revises: 8c8c4a3bb65d
Create Date: 2023-08-06 22:22:33.368197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc0b5aa9c96'
down_revision = '8c8c4a3bb65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course_Prerequisite',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Course_Prerequisite')
    # ### end Alembic commands ###
