"""Hey

Revision ID: eaa661a1dddb
Revises: 3446ca30c8c6
Create Date: 2023-08-15 00:36:31.023335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa661a1dddb'
down_revision = '3446ca30c8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Course_Prerequisite')
    with op.batch_alter_table('Course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Course', ['prerequisite_id'], ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prerequisite_id')

    op.create_table('Course_Prerequisite',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['Course.course_id'], name='Course_Prerequisite_prerequisite_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id', name='Course_Prerequisite_pkey')
    )
    # ### end Alembic commands ###
